/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_ADMIN_INVITE_FROM_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACES_OF_PLANTS_PRODUCTION_SECRETS_LLM_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "faces-of-plants-production-admin-site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "faces-of-plants-production-api-gateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "faces-of-plants-production-database-auth-js": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-cache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-data-sources": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-login-history": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-query-history": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-rate-limits": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-search-logs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-system-settings": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-database-user-collections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "faces-of-plants-production-frontend-site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}