/**
 * Plant Pathology Detector — ONNX inference in browser.
 *
 * Uses a pre-trained MobileNetV2 model (38 PlantVillage classes)
 * running via ONNX Runtime Web (WASM backend).
 *
 * The model must be generated by running: python scripts/convert-to-onnx.py
 */

import * as ort from 'onnxruntime-web';

// Configure ONNX Runtime to use WASM backend (guard for SSR)
if (typeof navigator !== 'undefined') {
  ort.env.wasm.numThreads = navigator.hardwareConcurrency || 4;
}

export interface PathologyResult {
  className: string;
  commonName: string;
  crop: string;
  isHealthy: boolean;
  confidence: number;
  severity: 'healthy' | 'low' | 'medium' | 'high' | 'critical';
}

// 38 PlantVillage classes
const CLASS_NAMES: string[] = [
  'Apple___Apple_scab',
  'Apple___Black_rot',
  'Apple___Cedar_apple_rust',
  'Apple___Healthy',
  'Blueberry___Healthy',
  'Cherry_(including_sour)___Powdery_mildew',
  'Cherry_(including_sour)___Healthy',
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
  'Corn_(maize)___Common_rust_',
  'Corn_(maize)___Northern_Leaf_Blight',
  'Corn_(maize)___Healthy',
  'Grape___Black_rot',
  'Grape___Esca_(Black_Measles)',
  'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
  'Grape___Healthy',
  'Orange___Haunglongbing_(Citrus_greening)',
  'Peach___Bacterial_spot',
  'Peach___Healthy',
  'Pepper,_bell___Bacterial_spot',
  'Pepper,_bell___Healthy',
  'Potato___Early_blight',
  'Potato___Late_blight',
  'Potato___Healthy',
  'Raspberry___Healthy',
  'Soybean___Healthy',
  'Squash___Powdery_mildew',
  'Strawberry___Leaf_scorch',
  'Strawberry___Healthy',
  'Tomato___Bacterial_spot',
  'Tomato___Early_blight',
  'Tomato___Late_blight',
  'Tomato___Leaf_Mold',
  'Tomato___Septoria_leaf_spot',
  'Tomato___Spider_mites Two-spotted_spider_mite',
  'Tomato___Target_Spot',
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
  'Tomato___Tomato_mosaic_virus',
  'Tomato___Healthy',
];

function parseClassName(className: string): {
  crop: string;
  condition: string;
  isHealthy: boolean;
} {
  const parts = className.split('___');
  const crop = (parts[0] || '').replace(/_/g, ' ').replace(/\(.*?\)/g, '').trim();
  const condition = (parts[1] || '').replace(/_/g, ' ').trim();
  const isHealthy = condition.toLowerCase() === 'healthy';
  return { crop, condition, isHealthy };
}

function getSeverity(confidence: number, isHealthy: boolean): PathologyResult['severity'] {
  if (isHealthy) return 'healthy';
  if (confidence >= 0.8) return 'critical';
  if (confidence >= 0.6) return 'high';
  if (confidence >= 0.4) return 'medium';
  return 'low';
}

/**
 * Pre-process image to 224x224 RGB tensor [1, 3, 224, 224].
 * Normalizes to ImageNet mean/std.
 */
async function preprocessImage(file: File): Promise<Float32Array> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const url = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(url);

      const canvas = document.createElement('canvas');
      canvas.width = 224;
      canvas.height = 224;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get canvas context'));
        return;
      }

      ctx.drawImage(img, 0, 0, 224, 224);
      const imageData = ctx.getImageData(0, 0, 224, 224);
      const { data } = imageData;

      // CHW format with ImageNet normalization
      const mean = [0.485, 0.456, 0.406];
      const std = [0.229, 0.224, 0.225];
      const tensor = new Float32Array(3 * 224 * 224);

      for (let i = 0; i < 224 * 224; i++) {
        for (let c = 0; c < 3; c++) {
          const pixel = data[i * 4 + c] / 255.0;
          tensor[c * 224 * 224 + i] = (pixel - mean[c]) / std[c];
        }
      }

      resolve(tensor);
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load image'));
    };

    img.src = url;
  });
}

let session: ort.InferenceSession | null = null;

/**
 * Load the ONNX model (cached after first load).
 */
async function loadModel(): Promise<ort.InferenceSession> {
  if (session) return session;

  session = await ort.InferenceSession.create('/models/plant-pathology.onnx', {
    executionProviders: ['wasm'],
    graphOptimizationLevel: 'all',
  });

  return session;
}

/**
 * Detect plant disease from a leaf image.
 *
 * @param file - Image file (JPEG/PNG, max 10MB)
 * @param topK - Number of top results to return (default: 5)
 * @returns Sorted results with confidence scores
 */
export async function detectPathology(
  file: File,
  topK: number = 5,
): Promise<PathologyResult[]> {
  const sess = await loadModel();
  const imageData = await preprocessImage(file);

  // Create input tensor [1, 3, 224, 224]
  const input = new ort.Tensor('float32', imageData, [1, 3, 224, 224]);

  // Run inference
  const output = await sess.run({ input });
  const probabilities = output.output.data;

  // Process results
  const results: PathologyResult[] = [];
  const probs = Float32Array.from(probabilities as any);

  for (let i = 0; i < CLASS_NAMES.length; i++) {
    const confidence = probs[i];
    const { crop, condition, isHealthy } = parseClassName(CLASS_NAMES[i]);

    results.push({
      className: CLASS_NAMES[i],
      commonName: condition,
      crop,
      isHealthy,
      confidence,
      severity: getSeverity(confidence, isHealthy),
    });
  }

  // Sort by confidence, return top K
  return results
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, topK);
}

/**
 * Check if the ONNX model is available.
 */
export async function isModelAvailable(): Promise<boolean> {
  try {
    const response = await fetch('/models/plant-pathology.onnx', { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
}
